#!/bin/sh
cache=/tmp/nix-options-man.txt
MANWIDTH=87 man configuration.nix 2>/dev/null|col -b > $cache
cat $cache|cat -n|grep -P "^ \d+\t       [^ ]+$"|sed 's| ||g;s|\t| |g'|fzf +s -d' ' --with-nth 2 --preview "tail +{1} '$cache'" --preview-window='60%' -q "$*"
